version: "3"

services:
  nextjs_frontend:
    build:
      context: ./HIKVISIONPG-FRONTEND-WEB-SITE
    image: nextjs_hikvision_frontend
    container_name: nextjs_frontend
    expose:
      - "3000"
    networks:
      - frontend_network
    restart: always

  nginx_frontend:
    image: nginx:alpine
    container_name: nginx_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    depends_on:
      - nextjs_frontend
    networks:
      - frontend_network
    restart: always

networks:
  frontend_network:
    driver: bridge
